### ISSUE TITLE
Please remove profile

### ISSUE THREAD

**Issue by hybrist** [bcambel/oss.io#29]
http://pythonhackers.com/user2/jkrems

**Comment by bcambel** [comment]
Hi Jan,

Do you mind to share the reason with me ? What kind of concerns do you have ? Send me an email if you don't want to indicate it publicly bahadir@hackersome.com
I will remove your page during the weekend ( Need to implement a opt-out list )

Thanks
Cheers,
Bahadir

**Comment by hybrist** [comment]
The reason is boring - it makes it look as if I signed up for that service while I didn't. And I'm not a big fan of people creating profile pages for me without my consent. :)

**Comment by bcambel** [comment]
I am very sorry for given that impression. That is completely not my aim. 

A quick question, do you mind if I add a note; indicating something like 

> The following data is part of public Github profiles. The following user actually is not a member of the platform.

and make it very clear. Or you don't want your name/image appear on the website at all ?

Thanks a lot for your time! I am sorry again.

**Comment by bcambel** [comment]
Hi, 

Check out http://pythonhackers.com/user2/jkrems

**Comment by hybrist** [comment]
Thanks!
