### ISSUE TITLE
Profile removal

### ISSUE THREAD

**Issue by jlslew** [bcambel/oss.io#41]
Hi,

Would you be kind enough to remove this user from **all variant** of your website, please?

http://java-hackers.com/user2/jlslew
http://pythonhackers.com/user2/jlslew
http://hackersome.com/user2/jlslew
...

Regards,
Jonathan.

**Comment by bcambel** [comment]
Soon to be deployed; https://github.com/bcambel/hackersome/commit/dfd536c51583b0671d986f53869d78fe74301f52

Cheers

**Comment by lukateras** [comment]
@jlslew He still holds your data: http://java-hackers.com/user2/jlslew
